services:
  nginx:
    image: nginx:alpine
    container_name: ansible-docker-nginx
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: ansible-docker-watchtower
    environment:
      - DOCKER_API_VERSION=1.44
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped